version: '{build}'
image: Visual Studio 2019

# Do not build on tags (GitHub, Bitbucket, GitLab, Gitea).
skip_tags: true

shallow_clone: true

branches:
  only:
    - master
    - develop

platform:
  - x64

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

before_build:
  - ps: cd ProjectV
  - ps: dotnet restore

build:
  verbosity: minimal

test:
  assemblies:
    - '**/*.Tests.dll'

# F# tests does not execute at all.
after_test:
  - ps: dotnet test "Tests/ProjectV.ContentDirectories.Tests/ProjectV.ContentDirectories.Tests.fsproj" --configuration $env:configuration --no-build

pull_requests:
    do_not_increment_build_number: true

nuget:  
    disable_publish_on_pr: true
