version: '{build}'
image: Visual Studio 2019 Preview

pull_requests:
    do_not_increment_build_number: true

branches:
    only:
    - master
    - develop

platform:
  - x64

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

nuget:  
    disable_publish_on_pr: true

before_build:
- cmd: cd ThingAppraiser
- cmd: dotnet restore

build:
  verbosity: minimal

notifications:
- provider: Email
  to:
  - vasar007@yandex.ru
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false
