version: '{build}'
image: Visual Studio 2019 Preview

branches:
    only:
    - master
    - develop

platform:
  - x64

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

install: 
- cmd: choco install dotnetcore-sdk

before_build:
- cmd: cd ThingAppraiser
- cmd: dotnet restore

build:
  verbosity: minimal

pull_requests:
    do_not_increment_build_number: true

nuget:  
    disable_publish_on_pr: true
