version: '{build}'
image: Visual Studio 2017

pull_requests:
    do_not_increment_build_number: true

branches:  
    only:
    - master
    - develop

nuget:  
    disable_publish_on_pr: true

before_build:
- cmd:
    - cd ThingAppraiser
    - dotnet restore
